# Generated by Django 3.0.6 on 2022-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')], default=1, verbose_name='Passenger gender'),
        ),
    ]
