# Generated by Django 3.0.6 on 2022-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220418_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='scan_udv_test',
        ),
        migrations.AddField(
            model_name='passenger',
            name='scan_udv',
            field=models.ImageField(blank=True, upload_to='udv', verbose_name='Scan of document'),
        ),
    ]
