# Generated by Django 3.0.6 on 2022-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220418_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super admin'), (2, 'System user'), (3, 'Employee'), (4, 'Passenger')], default=4, verbose_name='User role'),
        ),
    ]
