# Generated by Django 3.0.6 on 2022-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Photo on registration'),
        ),
    ]
