# Generated by Django 3.0.6 on 2022-05-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passenger_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='photo',
        ),
    ]
