# Generated by Django 3.0.6 on 2022-04-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Airline name')),
                ('logo', models.ImageField(blank=True, upload_to='airlines', verbose_name='Logo of Airline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=90, verbose_name='Name of the baggage')),
                ('description', models.CharField(blank=True, max_length=90, verbose_name='Description')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight of baggage')),
                ('number', models.IntegerField(default=1, verbose_name='Number of baggage (2 boxes)')),
                ('xray', models.ImageField(blank=True, upload_to='xrays', verbose_name='Xray of baggage')),
                ('status', models.IntegerField(choices=[(1, 'Airport From'), (2, 'Loading to the board'), (3, 'On the Board'), (4, 'Unoading from the board'), (5, 'Airport To'), (6, 'Arested')], default=1, verbose_name='Status of baggage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('from_location', models.CharField(max_length=90, verbose_name='City/Country from')),
                ('to_location', models.CharField(max_length=90, verbose_name='City/Country to')),
                ('time_start', models.DateTimeField()),
                ('time_finish', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Not used'), (2, 'Registration'), (3, 'Security control'), (4, 'Passport control start'), (5, 'Used'), (6, 'Passport control finish'), (7, 'Baggage')], default=1, verbose_name='Status')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tracking.Airline')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='users.Passenger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
