# Generated by Django 3.0.6 on 2022-04-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee'),
        ('tracking', '0002_remove_ticket_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='users.Passenger'),
            preserve_default=False,
        ),
    ]
