# Generated by Django 3.0.6 on 2022-04-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_ticket_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sector', models.CharField(max_length=1, verbose_name='Sector of place')),
                ('number', models.IntegerField(verbose_name='Number of place')),
                ('baggages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_pass', to='tracking.Baggage')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_pass', to='tracking.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
