# Generated by Django 3.0.6 on 2022-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_boardingpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardingpass',
            name='baggages',
        ),
        migrations.AddField(
            model_name='boardingpass',
            name='baggages',
            field=models.ManyToManyField(related_name='boarding_pass', to='tracking.Baggage'),
        ),
    ]
