# Generated by Django 3.0.6 on 2022-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20220430_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baggage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='baggage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='baggage',
            name='number',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not used'), (2, 'Registration'), (3, 'Security control'), (4, 'Used'), (5, 'Baggage')], default=1, verbose_name='Status'),
        ),
    ]
